server.port=${PORT:8080}
spring.application.name=consultoria-rh-api
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=e721fa3b9e3a9ef3702ec1a472a9b49e763e70e3df8e25e024cc2154646ea269
